[client]
httpRequestTimeout = 1000000

[token]
publisherEndpoint = ""
adminEndpoint = ""
registrationEndpoint = ""
tokenEndpoint = ""
username = ""
clientId = ""
clientSecret = ""
trustStoreLocation = ""
trustStorePassword = ""

[corsConfiguration]
corsConfigurationEnabled = true
accessControlAllowCredentials = false
accessControlAllowOrigins = ["*"]
accessControlAllowHeaders = ["authorization", "Access-Control-Allow-Origin", "Content-Type", "SOAPAction"]
accessControlAllowMethods = ["GET", "PUT", "POST", "DELETE", "PATCH", "OPTIONS"]
